In [3]:
import sys

print(sys.executable)

c:\Users\ashim\OneDrive\Desktop\Pustaksathi\PustakSathi\backend\.venv\Scripts\python.exe

In [6]:
import pandas as pd
import numpy as np

import string

In [7]:
df = pd.read_csv("../data/books.csv")

In [8]:
df.isna().sum()

ISBN         0
Title        0
Author       0
Year         0
Publisher    0
Blurb        0
dtype: int64

In [9]:
df.shape

(57510, 6)

In [10]:
df.describe(include="object")

C:\Users\ashim\AppData\Local\Temp\ipykernel_26312\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,ISBN,Title,Author,Publisher,Blurb
count,57510,57510,57510,57510,57510
unique,57510,52307,24041,4587,55308
top,0060973129,The Secret Garden,Stephen King,Ballantine Books,Free Delivery if order value from the seller i...
freq,1,11,257,1329,14

In [11]:
df[df["Year"]==0]

,ISBN,Title,Author,Year,Publisher,Blurb
114,3150000335,Kabale Und Liebe,Schiller,0,"Philipp Reclam, Jun Verlag GmbH","ISBNs moved from ,Das 1784 erschienene und ura..."
126,342311360X,Die Liebe in Den Zelten,Gabriel Garcia Marquez,0,Deutscher Taschenbuch Verlag (DTV),"51 Jahre, 9 Monate und 4 Tage wartet Florentin..."
207,0571197639,Poisonwood Bible Edition Uk,Barbara Kingsolver,0,Faber Faber Inc,is a story told by the wife and four daughter...
245,3596214629,"Herr Der Fliegen (Fiction, Poetry and Drama)",Golding,0,Fischer Taschenbuch Verlag GmbH,Eine Gruppe englischer Schuljungen gerät infol...
431,0590021117,Little House On the Prairie,Laura Ingall Wilder,0,Scholastic Inc,A family travels from the big woods of Wiscons...
...,...,...,...,...,...,...
56675,0552997994,Chocolat,Joanne Harris,0,Corgi,When the exotic stranger Vianne Rocher arrives...
56683,8408017918,"OP-CENTER, EL SILENCIO DEL KREMLIN",Tom Clancy,0,Planeta Pub Corp,"In Los Angeles, an explosion kills the head of..."
56757,3423122404,"Die Liebe in Den Zeiten Der Cholera (Fiction, ...",Gabriel Garcia Marquez,0,Deutscher Taschenbuch Verlag (DTV),"51 Jahre, 9 Monate und 4 Tage wartet Florentin..."
56898,0146000447,Five Letters From an Eastern Empire,Alasdair Gray,0,Penguin Putnam~trade,"Describing etiquette, government, irrigation, ..."
57075,0316648442,Business Edition Uk,Iain Banks,0,Little Brown Uk,Kate is a senior executive officer in a powerf...

In [12]:
df = df[df['Year'] != 0]

In [13]:
df["Title2"] = df["Title"].str.lower()
df["Title2"] = df["Title2"].str.translate(str.maketrans("", "", string.punctuation))

In [14]:
# Wasted an hour on this code which never made out {#SAHEED_CODE}


# df["Blurb_Count"] = df.groupby(["Title", "Author", "Blurb"])["Blurb"].transform("count")

# df = df.sort_values(["Title", "Author", "Blurb_Count"], ascending=[True, True, False])
# df["Common_Blurb"] = df.groupby(["Title", "Author"])["Blurb"].transform("first")

# df["Group_Max_Count"] = df.groupby(["Title", "Author"])["Blurb_Count"].transform("max")

# mask = (df["Group_Max_Count"] > 1) & (df["Blurb"] == df["Common_Blurb"]) | (df["Group_Max_Count"] <= 1)
# df_filtered = df[mask]

# df_clean = (
#     df_filtered.sort_values("Year", ascending=False)
#     .drop_duplicates(subset=["Title", "Author"])
#     .reset_index(drop=True)
# )

# df_clean = df_clean.drop(columns=["Blurb_Count", "Common_Blurb", "Group_Max_Count"])

In [15]:
df_clean = (
    df.sort_values("Year", ascending=False)
    .drop_duplicates(subset=["Title2"])
    .reset_index(drop=True)
)

df_clean

,ISBN,Title,Author,Year,Publisher,Blurb,Title2
0,0140201092,Outline of European Architecture (Pelican S.),Nikolaus Pevsner,2050,Penguin USA,One of the most widely read books on European ...,outline of european architecture pelican s
1,0140301690,Alice's Adventures in Wonderland and Through t...,Lewis Carroll,2050,Puffin Books,Young readers will be eager to sample the lite...,alices adventures in wonderland and through th...
2,0394701658,Three Plays of Eugene Oneill,Eugene O'Neill,2038,Vintage Books USA,These three plays exemplify Eugene O'Neil's ab...,three plays of eugene oneill
3,0671746103,MY TEACHER FRIED MY BRAINS (RACK SIZE) (MY TEA...,Coville,2030,Aladdin,The first day of seventh grade was probably th...,my teacher fried my brains rack size my teache...
4,0870449842,Crossing America,National Geographic Society,2030,National Geographic,This completely revised version of the perenni...,crossing america
...,...,...,...,...,...,...,...
50931,0060830484,Point Counter Point,Aldous Huxley,1928,Harpercollins,Aldous Huxley's lifelong concern with the dich...,point counter point
50932,0448089033,The Secret of the Old Mill (The Hardy Boys Mys...,Franklin W. Dixon,1927,Grosset &amp; Dunlap,Determined to learn the secret of the old mill...,the secret of the old mill the hardy boys myst...
50933,0684718081,The Sun Also Rises,Ernest Hemingway,1926,Scribner Book Company,The quintessential novel of the Lost Generatio...,the sun also rises
50934,0880297182,Ghosts of Old Europe,Hans Holzer,1920,Dorset Press,"The , offers a very different kind of tour to ...",ghosts of old europe
50935,0375703152,Cold Mountain Open Market Edit,Charles Frazier,1920,Vintage Books USA,is a novel about a soldier’s perilous journey...,cold mountain open market edit

In [16]:
df_clean["Author"] = df_clean["Author"].str.lower()
df_clean["Author"] = df_clean["Author"].str.translate(str.maketrans("", "", string.punctuation))

In [20]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords')
nltk.download('wordnet')
stop = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ashim\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ashim\AppData\Roaming\nltk_data...

In [21]:
def preprocess_text(row):
    row = str(row).lower()
    row = row.translate(str.maketrans("", "", string.punctuation))
    row = " ".join(word for word in row.split() if word not in stop)
    row = " ".join(lemmatizer.lemmatize(word) for word in row.split())
    return row

df_clean['Blurb'] = df_clean['Blurb'].apply(preprocess_text)

In [22]:
df_clean['text'] = df_clean[['Title2', 'Title2', 'Author', 'Author', 'Blurb']].agg(" ".join, axis=1)
df_clean

,ISBN,Title,Author,Year,Publisher,Blurb,Title2,text
0,0140201092,Outline of European Architecture (Pelican S.),nikolaus pevsner,2050,Penguin USA,one widely read book european architecture nik...,outline of european architecture pelican s,outline of european architecture pelican s out...
1,0140301690,Alice's Adventures in Wonderland and Through t...,lewis carroll,2050,Puffin Books,young reader eager sample literary genius trea...,alices adventures in wonderland and through th...,alices adventures in wonderland and through th...
2,0394701658,Three Plays of Eugene Oneill,eugene oneill,2038,Vintage Books USA,three play exemplify eugene oneils ability exp...,three plays of eugene oneill,three plays of eugene oneill three plays of eu...
3,0671746103,MY TEACHER FRIED MY BRAINS (RACK SIZE) (MY TEA...,coville,2030,Aladdin,first day seventh grade probably worst day dun...,my teacher fried my brains rack size my teache...,my teacher fried my brains rack size my teache...
4,0870449842,Crossing America,national geographic society,2030,National Geographic,completely revised version perennially popular...,crossing america,crossing america crossing america national geo...
...,...,...,...,...,...,...,...,...
50931,0060830484,Point Counter Point,aldous huxley,1928,Harpercollins,aldous huxley lifelong concern dichotomy passi...,point counter point,point counter point point counter point aldous...
50932,0448089033,The Secret of the Old Mill (The Hardy Boys Mys...,franklin w dixon,1927,Grosset &amp; Dunlap,determined learn secret old mill frank joe emp...,the secret of the old mill the hardy boys myst...,the secret of the old mill the hardy boys myst...
50933,0684718081,The Sun Also Rises,ernest hemingway,1926,Scribner Book Company,quintessential novel lost generation one ernes...,the sun also rises,the sun also rises the sun also rises ernest h...
50934,0880297182,Ghosts of Old Europe,hans holzer,1920,Dorset Press,offer different kind tour armchair traveler wa...,ghosts of old europe,ghosts of old europe ghosts of old europe hans...
50935,0375703152,Cold Mountain Open Market Edit,charles frazier,1920,Vintage Books USA,novel soldier’s perilous journey back beloved ...,cold mountain open market edit,cold mountain open market edit cold mountain o...

In [23]:
combined_df = df_clean[['ISBN', 'Title', 'text']]
combined_df

,ISBN,Title,text
0,0140201092,Outline of European Architecture (Pelican S.),outline of european architecture pelican s out...
1,0140301690,Alice's Adventures in Wonderland and Through t...,alices adventures in wonderland and through th...
2,0394701658,Three Plays of Eugene Oneill,three plays of eugene oneill three plays of eu...
3,0671746103,MY TEACHER FRIED MY BRAINS (RACK SIZE) (MY TEA...,my teacher fried my brains rack size my teache...
4,0870449842,Crossing America,crossing america crossing america national geo...
...,...,...,...
50931,0060830484,Point Counter Point,point counter point point counter point aldous...
50932,0448089033,The Secret of the Old Mill (The Hardy Boys Mys...,the secret of the old mill the hardy boys myst...
50933,0684718081,The Sun Also Rises,the sun also rises the sun also rises ernest h...
50934,0880297182,Ghosts of Old Europe,ghosts of old europe ghosts of old europe hans...
50935,0375703152,Cold Mountain Open Market Edit,cold mountain open market edit cold mountain o...

In [24]:
combined_df = combined_df.reset_index(drop=True)

In [25]:
combined_df

,ISBN,Title,text
0,0140201092,Outline of European Architecture (Pelican S.),outline of european architecture pelican s out...
1,0140301690,Alice's Adventures in Wonderland and Through t...,alices adventures in wonderland and through th...
2,0394701658,Three Plays of Eugene Oneill,three plays of eugene oneill three plays of eu...
3,0671746103,MY TEACHER FRIED MY BRAINS (RACK SIZE) (MY TEA...,my teacher fried my brains rack size my teache...
4,0870449842,Crossing America,crossing america crossing america national geo...
...,...,...,...
50931,0060830484,Point Counter Point,point counter point point counter point aldous...
50932,0448089033,The Secret of the Old Mill (The Hardy Boys Mys...,the secret of the old mill the hardy boys myst...
50933,0684718081,The Sun Also Rises,the sun also rises the sun also rises ernest h...
50934,0880297182,Ghosts of Old Europe,ghosts of old europe ghosts of old europe hans...
50935,0375703152,Cold Mountain Open Market Edit,cold mountain open market edit cold mountain o...

In [26]:
combined_df[["ISBN", "Title"]].to_csv("../data/books_meta.csv", index=False)

In [27]:
indices_title = pd.Series(combined_df.index, index=combined_df['Title'].str.lower().str.translate(str.maketrans("", "", string.punctuation)))
indices_title

Title
outline of european architecture pelican s                                        0
alices adventures in wonderland and through the looking glass puffin books        1
three plays of eugene oneill                                                      2
my teacher fried my brains rack size my teacher books                             3
crossing america                                                                  4
                                                                              ...
point counter point                                                           50931
the secret of the old mill the hardy boys mystery stories book 3              50932
the sun also rises                                                            50933
ghosts of old europe                                                          50934
cold mountain open market edit                                                50935
Length: 50936, dtype: int64

In [28]:
indices_isbn = pd.Series(combined_df.index, index=combined_df['ISBN'])
indices_isbn

ISBN
0140201092        0
0140301690        1
0394701658        2
0671746103        3
0870449842        4
              ...
0060830484    50931
0448089033    50932
0684718081    50933
0880297182    50934
0375703152    50935
Length: 50936, dtype: int64

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=100000, ngram_range=(1,2))
vectorized_matrix = vectorizer.fit_transform(combined_df['text'])

In [30]:
from sklearn.metrics.pairwise import cosine_similarity
def normalize_title(title):
    return (
        str(title)
        .strip()
        .lower()
        .translate(str.maketrans("", "", string.punctuation))
    )
def get_prediction(titles, n=12):
    selected_idx = [
        indices_title[normalize_title(title)]
        for title in titles
    ]
    user_vector = np.asarray(vectorized_matrix[selected_idx].mean(axis=0))
    sim_score = cosine_similarity(user_vector, vectorized_matrix)[0]
    sim_score[selected_idx] = -1
    sim_idx = np.argsort(sim_score)[::-1][:n]
    return combined_df["Title"].iloc[sim_idx].tolist()

In [31]:
Pred_list = get_prediction([
    "Little Women",
    "Anne of Green Gables",
    "The Secret Garden",
    "Charlotte's Web",
    "Heidi",
    "Black Beauty",
    "Treasure Island",
    "The Adventures of Tom Sawyer",
    "Alice's Adventures in Wonderland",
    "The Wind in the Willows"
])
Pred_list

["Anne of Green Gables (Children's Classics)",
 'Black Beauty (Penguin Popular Classics)',
 'WIND IN THE WILLOWS, THE',
 'The Secret Garden (Silver Elm Classic Series)',
 'Little Women (Modern Library College Editions)',
 'Anne of Green Gables (Bantam Starfire Book)',
 'The Adventures of Tom Sawyer (Penguin Popular Classics)',
 'Adventures of Tom Sawyer',
 'The Adventures of Tom Sawyer (Adventures of Tom Sawyer)',
 'Little Women (Signet Classic)',
 'Heidi (Kingfisher Classics)',
 'The Wind in the Willows (Puffin Classics)']